In [ ]:
import sys
sys.path.append('./qdarts')

from qdarts.experiment import Experiment
from qdarts.plotting import plot_polytopes

import numpy as np
import math
import matplotlib.pyplot as plt
import matplotlib.gridspec as gridspec


#import torch


ModuleNotFoundError: No module named 'h5py'

In [3]:
C_DD, C_DG = u.generate_capacitance_matrices()
tcs = np.zeros((c.K,c.K))
# tcs[0,1] = 50*1e-6
# tcs[1,0] = 50*1e-6

capacitance_config = {
        "C_DD" : C_DD,  #dot-dot capacitance matrix
        "C_Dg" : C_DG,  #dot-gate capacitance matrix
        "ks" : None,       #distortion of Coulomb peaks. NOTE: If None -> constant size of Coublomb peak 
}

tunneling_config = {
        "tunnel_couplings": tcs, #tunnel coupling matrix
        "temperature": 0.1,                   #temperature in Kelvin
        "energy_range_factor": 5,  #energy scale for the Hamiltonian generation. NOTE: Smaller -> faster but less accurate computation 
}

sensor_config = {
        "sensor_dot_indices": [1],  #Indices of the sensor dots
        "sensor_detunings": [-0.0005],  #Detuning of the sensor dots
        "noise_amplitude": {"fast_noise": 0.8*1e-6, "slow_noise": 1e-8}, #Noise amplitude for the sensor dots in eV
        "peak_width_multiplier": 15,  #Width of the sensor peaks in the units of thermal broadening m *kB*T/0.61.
}


In [4]:
experiment = Experiment(capacitance_config=capacitance_config, 
                        tunneling_config=tunneling_config, 
                        sensor_config=sensor_config)

EXPERIMENT INITIALIZED
-----------------------

                Capacitance model deployed with the following parameters:
                Dot-dot capacitances: 
                [[11.81655272  0.85889783  0.85889783]
 [ 0.85889783 11.17784802  0.85889783]
 [ 0.85889783  0.85889783  9.4116185 ]]
                Dot-gate capacitances: 
                [[8.70135598 1.21190253 1.04439638]
 [0.77253202 8.73935941 0.80705876]
 [1.00209725 0.79532171 6.7553017 ]]
                Size of Coulomb peaks V[n] is constant
                

            Sensor model deployed with the following parameters:   
            Sensor dot indices: [1]
            Sensor detunings: [-0.5] meV
            Coulomb peak width: 0.41 meV
            Slow noise amplitude: 0.01 ueV
            Fast noise amplitude: 0.8 ueV
            

            Tunneling model deployed with the following parameters:
            Tunneling matrix:
            [[1.e-20 1.e-20 1.e-20]
 [1.e-20 1.e-20 1.e-20]
 [1.e-20 1.e-20 1.e-20]]

In [5]:
xks, yks, csd_dataks, polytopesks, sensor_signalexp, _ = experiment.generate_CSD(
                                        x_voltages = np.linspace(0, 0.03, 250),  #V
                                        y_voltages = np.linspace(0, 0.03, 250),  #V
                                        plane_axes = [[1,0,0], [0,0,1]], #NOTE: with defauls use_virtual_gates = False, this means voltages.
                                        compute_polytopes = True,
                                        use_virtual_gates = False,
                                        use_sensor_signal=True)    

d:\!!!_PDF\Fizyka i matma studia\!!!_Leiden\!! projekty 2024_25\Evert van Niewenburg\potencial projects\Qdarts projects\qdarts_code\learning_parameters\./qdarts\tunneling_simulator.py:116: RuntimeWarning: invalid value encountered in scalar divide
  results[i] = np.sum(p*np.mean(g,axis=1))/np.sum(p)


In [6]:
plot, ax = u.plot_CSD(xks, yks, sensor_signalexp[:,:,0], polytopesks)


In [8]:
plot

<Figure size 256x256 with 1 Axes>

In [7]:
ax

<Axes: >